tab1vars <- c(
  "num_region",
  # Clinical characteristics
  "num_age",
  "d_age_cat",
  "num_dmgender",
  "num_dmWeight",
  "num_dmBmi",
  "d_dmBmi_cat",
  "d_dmHF_cat",
  "d_HFdiagnosis",
  "num_dmEtio_c1",
  "num_dmEflp",
  "prev_mi_cabg_pci",
  "d_dmDev_cat",
  "num_dmStroke",
  "num_dmAfib_c1",
  "num_dmPvd",
  "num_dmVte",
  "num_dmDiab_c1",
  "num_dmHyChol",
  "num_dmCopd",
  "num_dmApn",
  "num_dmHepa",
  "d_dmThy",
  "num_dmHT",
  "num_dmSmoking_c1",

  # Previous pharmacotherapy
  "num_mdDiurp",
  "d_loopDiurp",
  "d_loopDiurpdose_eqFurosemide",
  "num_mdALp",
  "d_arb_or_ace_or_arnip",
  "num_mdACEp",
  "num_mdATp",
  "num_mdARNIp",
  "num_mdBBp",
  "num_mdAmip",
  "num_mdAntiarp",
  "num_mdDigop",
  "num_mdCcbp",
  "num_mdAntiarp",
  "num_mdAntiplp",
  "num_mdStatp",
  "num_mdNitp",
  "num_mdACp",
  "num_mdNsaip",
  "num_mdAdepp",
  "num_mdInsp",

  # Clinical presentation at hospital admission
  "num_dmBpm",
  "d_dmBpm_cat",
  "num_dmBp1",
  "d_dmBp1_cat",
  "num_hsHosPresCli",
  "d_hsNyha_cat",
  "num_hsRal",
  "d_X_pulmc_alvoedema",
  "num_hsOed",
  "num_hsHf",
  "num_hsFacAf",
  "num_hsFacBrad",
  "num_hsFacMy",
  "num_hsFacUnh",
  "num_hsFacInf",
  "num_hsFacRen",
  "num_hsFacIat",
  "num_hsFacNonc",
  "num_hsFacVa",
  "num_hsFacAne",

  # Laboratory findings at hospital admission
  "num_hsNt",
  "num_hsBnp",
  "d_either_hsNtBnp",
  "num_hsTrop",
  "num_hsSod",
  "num_hsPot",
  "num_hsCre",
  "d_hsCKDEPI",
  "d_hsCKDEPI_cat",
  "num_hsBun",
  "num_hsUre",
  "num_hsBili",
  "num_hsCrp",
  "num_hsWbc",
  "num_hsHb",

  # ECG at hospital admission
  "num_dcRyth_c1",
  "num_dcLbbb",
  "d_qtcfridericia",

  # Echocardiography
  "num_dcEf",
  "d_dcEf_cat",
  "num_dcLvdd",
  "num_dcLvh",
  "d_LAVI",
  "num_dcLadim",
  "num_dcRsp",
  "num_dcAorReg",
  "num_dcMitReg",
  "num_dcTriCus",
  "num_dcRhCath",
  "num_dcRhcPap"
)

tab2vars <- c(
  # In-hospital management
  "num_hsIntr",
  "num_hsNitrat",
  "num_hsProDiu",

  # In-hospital management (oral medication)
  "num_mdDiurh",
  "d_loopDiurh",
  "d_loopDiurhdose_eqFurosemide",
  "num_mdALh",
  "d_arb_or_ace_or_arnih",
  "num_mdACEh",
  "num_mdATh",
  "num_mdARNIh",
  "num_mdBBh",
  "num_mdAmih",
  "num_mdAntiarh",
  "num_mdDigoh",
  "num_mdCcbh",
  "num_mdAntiarh",
  "num_mdAntiplh",
  "num_mdStath",
  "num_mdNith",
  "num_mdACh",
  "num_mdNsaih",
  "num_mdAdeph",
  "num_mdInsh",
  "d_dcCardiov_AF",
  "num_dcCora",
  "num_dcPci",

  # Clinical status at discharge
  "d_change_weight",
  "d_changepercent_weight",
  "d_dcNyha_cat",
  "improvment1class_dcNyha",
  "num_dcBpm",
  "d_dcBpm_cat",
  "num_dcBp1",
  "d_dcBp1_cat",

  # Laboratory findings on discharge
  "num_dcNt",
  "d_change_dcNt",
  "d_changepercent_dcNt",
  "num_dcBnp",
  "d_change_dcBnp",
  "d_changepercent_dcBnp",
  "d_changepercent_either_dcNtBnp",
  "num_dcSod",
  "num_dcPot",
  "d_change_Pot",
  "d_changepercent_Pot",
  "num_dcCre",
  "d_change_Cre",
  "d_changepercent_Cre",
  "d_changepercent_Cre_cat",
  "d_dcCKDEPI",
  "d_dcCKDEPI_cat",
  "d_change_CKDEPI",
  "d_changepercent_CKDEPI",
  "num_dcBun",
  "num_dcUre",
  "num_dcBili",
  "num_dcCrp",
  "num_dcWbc",
  "num_dcHb",
  "d_dcHb_cat",
  "d_change_Hb",
  "d_changepercent_Hb",

  # Pharmacotherapy at hospital discharge
  "num_mdDiurd",
  "d_loopDiurd",
  "d_loopDiurddose_eqFurosemide",
  "num_mdALd",
  "d_arb_or_ace_or_arnid",
  "num_mdACEd",
  "num_mdATd",
  "num_mdARNId",
  "num_mdBBd",
  "num_mdAmid",
  "num_mdAntiard",
  "num_mdDigod",
  "num_mdCcbd",
  "num_mdAntiard",
  "num_mdAntipld",
  "num_mdStatd",
  "num_mdNitd",
  "num_mdACd",
  "num_mdNsaid",
  "num_mdAdepd",
  "num_mdInsd"
)

modvars <- c(
  "d_dcEf_cat",
  "d_age_cat",
  "num_dmgender",
  "d_dmBmi_cat",
  "num_dmEtio_c1",
  "d_dmHF_cat",
  "num_dmStroke",
  "num_dmAfib_c1",
  "num_dmPvd",
  "num_dmDiab_c1",
  "num_dmCopd",
  "num_dmHepa",
  "num_dmDis",
  "num_dmDepr",
  "num_hsFacAf",
  "num_hsFacMy",
  "num_hsFacInf",
  "num_hsFacUnh",
  "num_hsFacRen",
  "num_dcMitReg",
  "num_dcTriCus",
  "num_hsIntr",
  "num_dcPci",
  "d_dmBpm_cat",
  "d_dmBp1_cat",
  "d_dcNyha_cat",
  "num_dmHyChol",
  "d_dcHb_cat",
  "num_mdDiurd",
  "num_mdALd",
  "d_arb_or_ace_or_arnid",
  "num_mdBBd"
)
