tab1vars <- c(
  "num_region",
  # Clinical characteristics
  "num_age",
  "d_age_cat",
  "num_dmgender",
  "d_dmBmi_cat",
  "num_dmBmi",
  "num_dmWeight",
  "d_HFdiagnosis",
  "d_dmHF_cat",
  "num_dmEtio_c1",
  "prev_mi_cabg_pci",
  "d_dmDev_cat",
  "num_dmStroke",
  "num_dmAfib_c1",
  "num_dmPvd",
  "num_dmVte",
  "num_dmDiab_c1",
  "num_dmHyChol",
  "num_dmCopd",
  "num_dmApn",
  "num_dmHepa",
  "d_dmThy",
  "num_dmHT",
  "num_dmDis",
  "num_dmDepr",
  "d_no_noncardiac_comorbs",
  "num_dmSmoking_c1",

  # Previous pharmacotherapy
  "num_mdDiurp",
  "d_loopDiurp",
  "d_loopDiurpdose_eqFurosemide",
  "d_loopDiurpdose_eqFurosemide40",
  "d_loopDiurpmod",
  "d_thiazideDiurp",
  "d_thiazideDiurpdose_eqHydrochlorotiazide",
  "d_thiazideDiurpdose_eqHydrochlorotiazide25",
  "num_mdALp",
  "num_mdALpdo",
  "d_ALpdose_25",
  "d_ALpmod",
  "d_arb_or_ace_or_arnip",
  "num_mdACEp",
  "num_mdATp",
  "num_mdARNIp",
  "num_mdBBp",
  "num_mdAmip",
  "num_mdAntiarp",
  "num_mdDigop",
  "num_mdCcbp",
  "num_mdAntiplp",
  "num_mdStatp",
  "num_mdNitp",
  "num_mdACp",
  "num_mdNsaip",
  "num_mdAdepp",
  "d_xanthinep",
  "nohyponatremiadrugsp",

  # Clinical presentation at hospital admission
  "num_dmBpm",
  "d_dmBpm_cat",
  "num_dmBp1",
  "d_dmBp1_cat",
  "num_hsHosPresCli",
  "d_hsNyha_cat",
  "num_hsRal",
  "d_X_pulmc_alvoedema",
  "num_hsOed",
  "d_reasonforhosp",
  "num_hsHf",
  "d_numhsFacarrhythmic",
  "d_numhsFacacsmi",
  "num_hsFacBrad",
  "num_hsFacMy",
  "num_hsFacUnh",
  "num_hsFacInf",
  "num_hsFacRen",
  "num_hsFacIat",
  "num_hsFacNonc",
  "num_hsFacAne",

  # Laboratory findings at hospital admission
  "num_hsNt",
  "num_hsBnp",
  "num_hsTrop",
  "num_hsSod",
  "num_hsPot",
  "num_hsGl",
  "num_hsCre",
  "d_hsCKDEPI",
  "d_hsCKDEPI_cat",
  "num_hsBun",
  "num_hsUre",
  "num_hsBili",
  "num_hsCrp",
  "num_hsWbc",
  "num_hsHb",

  # ECG at hospital admission
  "num_dcRyth",
  "num_dcLbbb",
  "d_qtcfridericia",

  # Echocardiography
  "num_dcEf",
  "d_dcEf_cat",
  "num_dcLvdd",
  "num_dcLvh",
  "d_LAVI",
  "num_dcLadim",
  "num_dcRsp",
  "num_dcAorSte",
  "num_dcAorReg",
  "num_dcMitReg",
  "num_dcTriCus"
)

tab2vars <- c(
  # In-hospital management
  "num_hsIntr",
  "num_hsNitrat",
  "num_hsProDiu",

  # In-hospital management (oral medication)
  "num_mdDiurh",
  "d_loopDiurh",
  "d_loopDiurhdose_eqFurosemide",
  "d_loopDiurhdose_eqFurosemide80",
  "d_loopDiurhmod",
  "d_thiazideDiurh",
  "d_thiazideDiurhdose_eqHydrochlorotiazide",
  "d_thiazideDiurhdose_eqHydrochlorotiazide25",
  "num_mdALh",
  "num_mdALhdo",
  "d_ALhdose_25",
  "d_ALhmod",
  "d_arb_or_ace_or_arnih",
  "num_mdACEh",
  "num_mdATh",
  "num_mdARNIh",
  "num_mdBBh",
  "num_mdAmih",
  "num_mdAntiarh",
  "num_mdDigoh",
  "num_mdCcbh",
  "num_mdAntiplh",
  "num_mdStath",
  "num_mdNith",
  "num_mdACh",
  "num_mdNsaih",
  "num_mdAdeph",
  "d_xanthineh",
  "nohyponatremiadrugsh",
  "num_dcCora",
  "num_dcPci",

  # Clinical status at discharge
  "num_dcVital",
  "d_lengtofstay",
  "d_lengtofstay_cat",
  "num_dcIccu_c1",
  "num_dcIccu",
  "d_dcIccu_cat",
  "num_dcRal",
  "num_dcJvp",
  "num_dcEff",
  "num_dcHep",
  "num_dcOed",
  "d_residual_congestion",
  "d_change_weight",
  "d_changepercent_weight",
  "d_change_weight_cat",
  "d_dcNyha_cat",
  "improvment1class_dcNyha",
  "num_dcBpm",
  "d_dcBpm_cat",
  "num_dcBp1",
  "d_dcBp1_cat",
  "d_change_Bp1",
  "d_changepercent_Bp1",

  # Laboratory findings on discharge
  "num_dcNt",
  "d_change_dcNt",
  "d_changepercent_dcNt",
  "num_dcBnp",
  "d_change_dcBnp",
  "d_changepercent_dcBnp",
  "d_changepercent_either_dcNtBnp",
  "num_dcSod",
  "num_dcPot",
  "d_change_Pot",
  "d_changepercent_Pot",
  "num_dcGl",
  "num_dcCre",
  "d_change_Cre",
  "d_changepercent_Cre",
  "d_changepercent_Cre_cat",
  "d_dcCKDEPI",
  "d_dcCKDEPI_cat",
  "d_change_CKDEPI",
  "d_changepercent_CKDEPI",
  "num_dcBun",
  "num_dcUre",
  "num_dcBili",
  "num_dcCrp",
  "num_dcWbc",
  "num_dcHb",
  "d_dcHb_cat",
  "d_change_Hb",
  "d_changepercent_Hb",

  # Pharmacotherapy at hospital discharge
  "num_mdDiurd",
  "d_loopDiurd",
  "d_loopDiurhmod",
  "d_loopDiurddose_eqFurosemide",
  "d_loopDiurddose_eqFurosemide40",
  "d_thiazideDiurd",
  "d_thiazideDiurddose_eqHydrochlorotiazide",
  "d_thiazideDiurddose_eqHydrochlorotiazide25",
  "num_mdALd",
  "num_mdALddo",
  "d_ALddose_25",
  "d_arb_or_ace_or_arnid",
  "num_mdACEd",
  "num_mdATd",
  "num_mdARNId",
  "num_mdBBd",
  "num_mdAmid",
  "num_mdDigod",
  "num_mdCcbd",
  "num_mdAntiard",
  "num_mdAntipld",
  "num_mdStatd",
  "num_mdNitd",
  "num_mdACd",
  "num_mdNsaid",
  "num_mdAdepd",
  "d_xanthined",
  "nohyponatremiadrugsd"
)

tabmeanvars <- c(
  "d_change_weight",
  "d_changepercent_weight"
)

logvars <- c(
  # Clinical characteristics
  "num_age",
  "num_dmgender",
  "num_dmBmi",
  "num_dmEtio_c1",
  "num_dmStroke",
  "num_dmPvd",
  "num_dmDiab_c1",
  "num_dmCopd",
  "num_dmHepa",
  "d_dmThy",
  "num_dmDis",
  "num_dmDepr",
  "num_dmSmoking_c1",

  # Heart failure
  "num_dcEf",
  "num_dcAorSte",
  "num_dcMitReg",
  "num_dcTriCus",
  "d_reasonforhosp",
  "num_dcRyth",

  # Clinical and laboratory presentation at admission
  "d_hsNyha_cat",
  "num_dmBpm",
  "num_dmBp1",
  "d_hsCKDEPI",
  "num_hsPot",
  "num_hsHb",

  # Previous pharmacotherapy (before hospital admission)
  "d_thiazideDiurp",
  "d_loopDiurpmod",
  "num_mdALp",
  "d_arb_or_ace_or_arnip",
  "num_mdBBp",
  "num_mdAmip",
  "num_mdAntiarp",
  "num_mdDigop",
  "num_mdCcbp",
  "num_mdAdepp",
  "d_xanthinep"
)

coxvars <- c(
  # Clinical characteristics
  "num_age",
  "num_dmgender",
  "num_dmBmi",
  "num_dmEtio_c1",
  "num_dmStroke",
  "num_dmPvd",
  "num_dmDiab_c1",
  "num_dmCopd",
  "num_dmHepa",
  "d_dmThy",
  "num_dmDis",
  "num_dmDepr",
  # "dmHyChol",

  "num_dmSmoking_c1",

  # Heart failure
  "num_dcEf",
  "num_dcAorSte",
  "num_dcMitReg",
  "num_dcTriCus",
  "d_reasonforhosp",
  "num_dcRyth",

  # In-hospital course
  "num_hsIntr",
  "num_dcPci",

  # Clinical and laboratory presentation at discharge
  "d_residual_congestion",
  "d_dcNyha_cat",
  "num_dcBpm",
  "num_dcBp1",
  "d_dcCKDEPI",
  "num_dcPot",
  "num_dcHb",

  # Discharge pharmacotherapy
  "d_loopDiurd",
  "num_mdALd",
  "d_arb_or_ace_or_arnid",
  "num_mdBBd",
  "num_mdAmid"
)

predvarsmult <- c(
  # Clinical characteristics
  "num_age",
  "num_dmgender",
  "num_dmBmi",
  "num_dmEtio_c1",
  "num_dmStroke",
  "num_dmPvd",
  "num_dmDiab_c1",
  "num_dmCopd",
  "num_dmHepa",
  "d_dmThy",
  "num_dmDis",
  "num_dmDepr",
  "num_dmSmoking_c1",

  # Heart failure
  "num_dcEf",
  "d_reasonforhosp",
  "num_dcRyth",

  # In-hospital course
  "num_hsIntr",
  "d_changepercent_weight",

  # Clinical and laboratory presentation at discharge
  "d_residual_congestion",
  "d_dcNyha_cat",
  "num_dcBp1",
  "d_changepercent_CKDEPI",

  # Pharmacotherapy during hospitalization
  "d_thiazideDiurh",
  "d_loopDiurhmod",
  "num_mdALh",
  "d_arb_or_ace_or_arnih",
  "num_mdBBh",
  "num_mdAmih",
  "num_mdAntiarh",
  "num_mdDigoh"
)
