
```{r forestout, cache=cacheon}
survforestfunc <- function(time, event, eventname) {
  out <- data.frame(matrix(NA, ncol = 6, nrow = 4))

  colnames(out) <- c("Outcome", "natremia", "loghr", "lci", "uci", "hrpprint")

  out[1, 1] <- eventname
  out[, 2] <- levels(edata$natremia)
  ## adjusted individual covariates

  amod <- with(imp, coxph(formula(paste0(
    "Surv(", time, ",", event, " == 1) ~ relevel(natremia, ref = 'Normo/Normo') + ", paste(coxvars, collapse = " + ")
  ))))

  ## df the number of events minus the regression coefficients.
  ## There is support for this from middle of page 149 of the book by Parmer & Machin (ISBN 0471936405)
  asmod <- summary(pool(amod,
    dfcom =
      (amod$analyses[[1]]$nevent - length(amod$analyses[[1]]$coefficients))
  ))

  out[, 3] <- c(asmod$estimate[1:3], NA)

  out[, 4] <- c(asmod$estimate[1:3] - global_z05 * asmod$std.error[1:3], NA)
  out[, 5] <- c(asmod$estimate[1:3] + global_z05 * asmod$std.error[1:3], NA)

  out[, 6] <- c(paste0(
    fn(exp(asmod$estimate[1:3]), dig = 2),
    " (", fn(exp(asmod$estimate[1:3] - global_z05 * asmod$std.error[1:3]), dig = 2),
    "-", fn(exp(asmod$estimate[1:3] + global_z05 * asmod$std.error[1:3]), dig = 2), "), ",
    fn(asmod$p.value[1:3], dig = 3, p = TRUE)
  ), "ref")
  return(out)
}


out3 <- survforestfunc(
  time = "outtime_death",
  event = "out_deathcv",
  eventname = "CV mortality"
)
out4 <- survforestfunc(
  time = "outtime_death",
  event = "out_deathhf",
  eventname = "HF mortality"
)
out5 <- survforestfunc(
  time = "outtime_hosp",
  event = "out_hosp",
  eventname = "First hospitalisation"
)
out6 <- survforestfunc(
  time = "outtime_hospcv",
  event = "out_hospcv",
  eventname = "First CV hospitalisation"
)
out7 <- survforestfunc(
  time = "outtime_hosphf",
  event = "out_hosphf",
  eventname = "First HF hospitalisation"
)

forestdata <- rbind(
  out3, out4, out5, out6, out7
) %>%
  mutate(order = n():1)
```

```{r forestoutplot, cache=cacheon, dependson="forestout", fig.width=9, fig.height=6}

cextext <- 1

minmy <- round(exp(min(forestdata$lci, na.rm = T)), 1)
maxmy <- round(exp(max(forestdata$uci, na.rm = T)), 1)

# c(bottom, left, top, right)
par(mar = c(4, 24, 0, 0) + 0.2)

plotCI(
  x = forestdata$loghr, y = forestdata$order,
  li = forestdata$lci,
  ui = forestdata$uci,
  err = "x",
  cex = 1.5,
  xlim = c(
    log(minmy),
    log(maxmy)
  ),
  xlab = NA,
  ylim = c(1, nrow(forestdata) + 1),
  axes = FALSE,
  ylab = NA,
  main = NA,
  pch = 22,
  pt.bg = global_cols[c(2, 4, 6, 8)],
  col = global_cols[c(2, 4, 6, 8)],
  lwd = 2
)

abline(v = log(1), lty = 2)

axis(1,
  cex.axis = cextext, at = log(c(minmy, 1, maxmy)),
  labels = c(minmy, 1, maxmy)
)

axis(2,
  at = nrow(forestdata) + 1,
  labels = "Outcome",
  cex.axis = cextext, tick = FALSE, las = 2, line = 23, hadj = 0, font = 2
)
axis(2,
  at = forestdata$order,
  labels = forestdata$Outcome,
  cex.axis = cextext, tick = FALSE, las = 2, line = 23, hadj = 0
)

axis(2,
  at = forestdata$order,
  labels = forestdata$natremia,
  cex.axis = cextext, tick = FALSE, las = 2, line = 13.5, hadj = 0
)

axis(2,
  at = nrow(forestdata) + 1,
  labels = "Adjusted HR (95% CI), p-value",
  cex.axis = cextext, tick = FALSE, las = 2, line = 3, hadj = 0.5, font = 2
)

axis(2,
  at = forestdata$order,
  labels = forestdata$hrpprint,
  cex.axis = cextext, tick = FALSE, las = 2, line = 3, hadj = 0.5
)

axis(1,
  at = (log(maxmy) + log(minmy)) / 2, cex.axis = cextext,
  labels = "Adjusted HR (95% CI)", line = 2, tick = FALSE
)
```
