
```{r outsub, cache=cacheon}
survsubfunc <- function(time, event, xvar, xvarname, nomodvar = xvar) {
  levsn <- levels(edata %>% pull(natremia))

  if (xvarname == "Overall") {
    out <- data.frame(matrix(NA, ncol = 7, nrow = 3))
    colnames(out) <- c("Subgroup", "Natremia", "HR (95% CI)", "p", "coef", "lci", "uci")

    out[1, 1] <- xvarname
    out[1:3, 2] <- levsn[1:3]

    ## adjusted individual covariates
    amod <- with(imp, coxph(formula(paste0(
      "Surv(", time, ",", event, " == 1) ~ relevel(natremia, ref = 'No/No') + ",
      paste(coxvars, collapse = " + ")
    ))))

    ## df the number of events minus the regression coefficients.
    ## There is support for this from middle of page 149 of the book by Parmer & Machin (ISBN 0471936405)
    asmod <- summary(pool(amod,
      dfcom =
        (amod$analyses[[1]]$nevent - length(amod$analyses[[1]]$coefficients))
    ))

    out[1:3, 3] <- paste0(
      fn(exp(asmod$estimate[1:3]), dig = 2),
      " (", fn(exp(asmod$estimate[1:3] - global_z05 * asmod$std.error[1:3]), dig = 2),
      "-", fn(exp(asmod$estimate[1:3] + global_z05 * asmod$std.error[1:3]), dig = 2), ")"
    )

    out[1:3, 5] <- asmod$estimate[1:3]
    out[1:3, 6] <- asmod$estimate[1:3] - global_z05 * asmod$std.error[1:3]
    out[1:3, 7] <- asmod$estimate[1:3] + global_z05 * asmod$std.error[1:3]
  } else {
    levs <- levels(edata %>% pull(!!sym(xvar)))

    out <- data.frame(matrix(NA, ncol = 7, nrow = length(levs) * 3 + 1))
    colnames(out) <- c("Subgroup", "Natremia", "HR (95% CI)", "p", "coef", "lci", "uci")

    out[1, 1] <- xvarname
    out[2:nrow(out), 2] <- rep(levsn[1:3], length(levs))
    out[2:nrow(out), 1] <- rep(paste0("  ", levs), each = length(levsn) - 1)

    coxvaruse <- coxvars[!coxvars %in% c(xvar, nomodvar)]
    
    for (i in seq_along(levs)) {
      ## adjusted individual covariates
      amod <- with(imp, coxph(formula(paste0(
        "Surv(", time, ",", event, " == 1) ~ relevel(natremia, ref = 'No/No') * relevel(",
        xvar, ", ref = '", levs[i], "') + ",
        paste(coxvaruse, collapse = " + ")
      ))))

      ## df the number of events minus the regression coefficients.
      ## There is support for this from middle of page 149 of the book by Parmer & Machin (ISBN 0471936405)
      asmod <- summary(pool(amod,
        dfcom =
          (amod$analyses[[1]]$nevent - length(amod$analyses[[1]]$coefficients))
      ))

      out[((i - 1) * 2 + i + 1):((i - 1) * 2 + i + 3), 3] <- paste0(
        fn(exp(asmod$estimate[1:3]), dig = 2),
        " (", fn(exp(asmod$estimate[1:3] - global_z05 * asmod$std.error[1:3]), dig = 2),
        "-", fn(exp(asmod$estimate[1:3] + global_z05 * asmod$std.error[1:3]), dig = 2), ")"
      )

      out[((i - 1) * 2 + i + 1):((i - 1) * 2 + i + 3), 5] <- asmod$estimate[1:3]
      out[((i - 1) * 2 + i + 1):((i - 1) * 2 + i + 3), 6] <- asmod$estimate[1:3] - global_z05 * asmod$std.error[1:3]
      out[((i - 1) * 2 + i + 1):((i - 1) * 2 + i + 3), 7] <- asmod$estimate[1:3] + global_z05 * asmod$std.error[1:3]

      if (i == 1) {
        amodnoint <- with(imp, coxph(formula(paste0(
          "Surv(", time, ",", event, " == 1) ~ relevel(natremia, ref = 'No/No') + relevel(", 
          xvar, ", ref = '", levs[i], "') + ",
          paste(coxvaruse, collapse = " + ")
        ))))

        int <- D1(amod, amodnoint)

        out[1, 4] <- fn(int$result[4], dig = 3, p = TRUE)
      }
    }
  }
  return(out)
}

survsubfunc2 <- function(time2, event2) {
  forestdata <- survsubfunc(
    time = time2,
    event = event2,
    xvarname = "Overall"
  )
  forestdata <- rbind(
    forestdata,
    survsubfunc(
      time = time2,
      event = event2,
      xvar = "d_age_cat",
      xvarname = "Age (years)", 
      nomodvar = "num_age"
    )
  )
  forestdata <- rbind(
    forestdata,
    survsubfunc(
      time = time2,
      event = event2,
      xvar = "num_dmgender",
      xvarname = "Sex"
    )
  )
  forestdata <- rbind(
    forestdata,
    survsubfunc(
      time = time2,
      event = event2,
      xvar = "d_dcEf_cat",
      xvarname = "LVEF (%)",
      nomodvar = "num_dcEf"
    )
  )
  forestdata <- rbind(
    forestdata,
    survsubfunc(
      time = time2,
      event = event2,
      xvar = "d_dcCKDEPI_cat",
      xvarname = "eGFR (mL/min/1.73 m²)", 
      nomodvar = "d_dcCKDEPI"
    )
  )
  forestdata <- rbind(
    forestdata,
    survsubfunc(
      time = time2,
      event = event2,
      xvar = "num_dmDiab_c1",
      xvarname = "Diabetes"
    )
  )
}
```

```{r outsubplot, cache=cacheon, dependson="outsub"}
plotforest <- function(forestdata, adds) {
  cextext <- 1

  forestdata <- forestdata %>%
    mutate(
      Subgroup = str_replace_all(Subgroup, ">=", "\u2265"),
      Subgroup = str_replace_all(Subgroup, "<=", "\u2264")
    )

  minmy <- round(exp(min(forestdata$lci, na.rm = T)), 2)
  maxmy <- round(exp(max(forestdata$uci, na.rm = T)), 1)

  g1 <- rev(forestdata %>% filter(is.na(Natremia) | Natremia == "Yes/Yes"))
  g2 <- rev(forestdata %>% filter(is.na(Natremia) | Natremia == "Yes/No"))
  g3 <- rev(forestdata %>% filter(is.na(Natremia) | Natremia == "No/Yes"))

  # c(bottom, left, top, right)
  par(mar = c(4, 28, 0, 3.5) + 0.2)

  add1 <- adds[1]
  add2 <- adds[2]

  plotCI(
    x = g1$coef, y = rev(1:nrow(g1)),
    li = g1$lci,
    ui = g1$uci,
    err = "x",
    cex = 1,
    xlim = c(
      log(minmy),
      log(maxmy) + add2
    ),
    xlab = NA,
    ylim = c(1, nrow(g1) + 2),
    axes = FALSE,
    ylab = NA,
    main = NA,
    pch = 22,
    pt.bg = global_cols[2],
    col = global_cols[2],
    lwd = 2
  )

  plotCI(
    x = g2$coef + add1, y = rev(1:nrow(g2)),
    li = g2$lci + add1,
    ui = g2$uci + add1,
    err = "x",
    cex = 1,
    xlab = NA,
    axes = FALSE,
    ylab = NA,
    main = NA,
    pch = 22,
    pt.bg = global_cols[4],
    col = global_cols[4],
    add = T,
    lwd = 2
  )

  plotCI(
    x = g3$coef + add2, y = rev(1:nrow(g3)),
    li = g3$lci + add2,
    ui = g3$uci + add2,
    err = "x",
    cex = 1,
    xlab = NA,
    axes = FALSE,
    ylab = NA,
    main = NA,
    pch = 22,
    pt.bg = global_cols[6],
    col = global_cols[6],
    add = T,
    lwd = 2
  )

  abline(v = log(1), lty = 2)
  abline(v = log(1) + add1, lty = 2)
  abline(v = log(1) + add2, lty = 2)

  axis(1,
    cex.axis = cextext, at = log(c(minmy, 1, maxmy)),
    labels = c(minmy, 1, maxmy)
  )
  axis(1,
    cex.axis = cextext, at = log(c(minmy, 1, maxmy)) + add1,
    labels = c(minmy, 1, maxmy)
  )
  axis(1,
    cex.axis = cextext, at = log(c(minmy, 1, maxmy)) + add2,
    labels = c(minmy, 1, maxmy)
  )

  axis(2,
    at = nrow(g1) + 1,
    labels = "Subgroup",
    cex.axis = cextext, tick = FALSE, las = 2, line = 27, hadj = 0, font = 2
  )
  axis(2,
    at = rev(1:nrow(g1)),
    labels = g1$Subgroup,
    cex.axis = cextext, tick = FALSE, las = 2, line = 27, hadj = 0
  )

  axis(2,
    at = nrow(g1) + 1,
    labels = "Yes/Yes",
    cex.axis = cextext, tick = FALSE, las = 2, line = 18, hadj = 0.5, font = 2,
    col.axis = global_cols[2]
  )
  axis(2,
    at = rev(1:nrow(g1)),
    labels = g1$`HR (95% CI)`,
    cex.axis = cextext, tick = FALSE, las = 2, line = 18, hadj = 0.5,
    col.axis = global_cols[2]
  )

  axis(2,
    at = nrow(g1) + 2,
    labels = "Adjusted HR (95% CI)",
    cex.axis = cextext, tick = FALSE, las = 2, line = 10, hadj = 0.5, font = 2
  )
  axis(2,
    at = nrow(g1) + 1,
    labels = "Yes/No",
    cex.axis = cextext, tick = FALSE, las = 2, line = 10, hadj = 0.5, font = 2,
    col.axis = global_cols[4]
  )
  axis(2,
    at = rev(1:nrow(g2)),
    labels = g2$`HR (95% CI)`,
    cex.axis = cextext, tick = FALSE, las = 2, line = 10, hadj = 0.5,
    col.axis = global_cols[4]
  )

  axis(2,
    at = nrow(g1) + 1,
    labels = "No/Yes",
    cex.axis = cextext, tick = FALSE, las = 2, line = 2, hadj = 0.5, font = 2,
    col.axis = global_cols[6]
  )
  axis(2,
    at = rev(1:nrow(g3)),
    labels = g3$`HR (95% CI)`,
    cex.axis = cextext, tick = FALSE, las = 2, line = 2, hadj = 0.5,
    col.axis = global_cols[6]
  )

  axis(2,
    at = rev(nrow(g1) + 1),
    labels = "P interaction",
    cex.axis = cextext, tick = FALSE, las = 1, line = -20.1, hadj = 0.5, font = 2
  )
  axis(2,
    at = rev(1:nrow(g1)),
    labels = g1$p,
    cex.axis = cextext, tick = FALSE, las = 1, line = -20.1, hadj = 0.5
  )

  axis(1,
    at = (log(maxmy) + log(minmy)) / 2, cex.axis = cextext,
    labels = "Yes/Yes", line = 1, tick = FALSE,
    col.axis = global_cols[2]
  )
  axis(1,
    at = (log(maxmy) + log(minmy)) / 2 + add1, cex.axis = cextext,
    labels = "Yes/No", line = 1, tick = FALSE,
    col.axis = global_cols[4]
  )
  axis(1,
    at = (log(maxmy) + log(minmy)) / 2 + add2, cex.axis = cextext,
    labels = "No/Yes", line = 1, tick = FALSE,
    col.axis = global_cols[6]
  )
  axis(1,
    at = (log(maxmy) + log(minmy)) / 2 + add1, cex.axis = cextext,
    labels = "Adjusted HR (95% CI)", line = 2, tick = FALSE
  )
}
```

```{r outsubacdeathhfh, cache=cacheon, dependson="outsub"}
deathachosphf <- survsubfunc2(
  time2 = "outtime_hosphf",
  event2 = "out_deathhosphf"
)
```

\blandscape

```{r forestcdeathhfh, cache=cacheon, dependson=c("outsubacdeathhfh", "outsubplot"), fig.cap="Subgroups All-cause mortality/First HFH", fig.width=10, fig.height=5}
plotforest(deathachosphf, adds = c(2.5, 5))
```

\elandscape

```{r outsubdeath, cache=cacheon, dependson="outsub"}
death <- survsubfunc2(
  time2 = "outtime_death",
  event2 = "out_death"
)
```

\blandscape

```{r forestdeath, cache=cacheon, dependson=c("outsubdeath", "outsubplot"), fig.cap="Subgroups All-cause mortality", fig.width=10, fig.height=5}
plotforest(death, adds = c(3.2, 6.4))
```

\elandscape
